CREATE DATABASE RELATION;
USE RELATION;
CREATE TABLE RELATION1(
FNAME VARCHAR (255) NOT NULL,
LNAME VARCHAR (255) NOT NULL,
RID INT PRIMARY KEY,
DEPT VARCHAR (200)
);
CREATE TABLE RELATION2(
ORDERID INT NOT NULL,
RID INT FOREIGN KEY REFERENCES RELATION1(RID),
PURCHASE_AMT INT NOT NULL,
QTY INT NOT NULL
);

INSERT INTO RELATION1 VALUES ('PRIYANKA','M S',1001,'MBA');
INSERT INTO RELATION1 VALUES ('DHARSHINI','M S',1002,'EIE');
INSERT INTO RELATION1 VALUES ('ARAVINDHA','M S',1003,'ECE');

INSERT INTO RELATION2 VALUES (1,1001,50000,20);
INSERT INTO RELATION2 VALUES (2,1002,60000,15);
INSERT INTO RELATION2 VALUES (3,1003,30000,10);

SELECT * FROM RELATION2

SELECT RELATION2.RID,RELATION1.FNAME,RELATION1.LNAME,RELATION2.QTY,RELATION2.PURCHASE_AMT
FROM RELATION1
INNER JOIN RELATION2
ON RELATION1.RID=RELATION2.RID;